# Generated by Django 4.2.1 on 2023-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0008_postlike_delete_reaction"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts", to="likes.postlike"
            ),
        ),
    ]
