# Generated by Django 4.2.1 on 2023-05-14 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
