# Generated by Django 4.2.1 on 2023-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
