# Generated by Django 4.2.1 on 2023-05-16 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_post_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023,
                    5,
                    16,
                    12,
                    17,
                    51,
                    874137,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
