# Generated by Django 4.2.1 on 2023-05-11 20:38

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_followers_profile_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                null=True, upload_to=profiles.models.profile_image_file_path
            ),
        ),
    ]
