# Generated by Django 4.2.1 on 2023-05-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="dislike",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="like",
        ),
        migrations.AddField(
            model_name="reaction",
            name="reaction",
            field=models.ForeignKey(
                blank=True,
                choices=[("LIKE", "Like"), ("DISLIKE", "Dislike")],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
