# Generated by Django 4.2.1 on 2023-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0003_reaction_user_alter_reaction_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="reaction",
        ),
        migrations.AddField(
            model_name="reaction",
            name="dislike",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reaction",
            name="like",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
