# Generated by Django 4.2.1 on 2023-05-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0004_remove_reaction_reaction_reaction_dislike_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="dislike",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="like",
        ),
        migrations.AddField(
            model_name="reaction",
            name="reaction",
            field=models.CharField(
                choices=[("LIKE", "Like"), ("DISLIKE", "Dislike")],
                default=1,
                max_length=63,
            ),
            preserve_default=False,
        ),
    ]
