# Generated by Django 4.2.1 on 2023-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "likes",
            "0005_remove_reaction_dislike_remove_reaction_like_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="reaction",
        ),
        migrations.AddField(
            model_name="reaction",
            name="dislike",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reaction",
            name="like",
            field=models.IntegerField(default=1),
        ),
    ]
