# Generated by Django 4.2.1 on 2023-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0006_remove_reaction_reaction_reaction_dislike_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="dislike",
            field=models.IntegerField(
                choices=[(1, "Like It"), (-1, "Dislike It")]
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="like",
            field=models.IntegerField(
                choices=[(1, "Like It"), (-1, "Dislike It")]
            ),
        ),
    ]
