# Generated by Django 4.2.1 on 2023-05-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_remove_post_likes"),
        ("likes", "0009_reaction_delete_postlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reaction",
                to="posts.post",
            ),
        ),
    ]
