# Generated by Django 4.2.1 on 2023-05-14 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0012_alter_like_post_alter_like_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="user",
            new_name="user_is_like",
        ),
    ]
