# Generated by Django 4.2.1 on 2023-05-14 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("likes", "0013_rename_user_like_user_is_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="user_is_like",
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
